import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from './context/auth-context'
import { Header } from '@/components/header/header'
import { MenuProvider } from './context/MenuContext'
import GoogleAnalytics from '@/components/GoogleAnalytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1 container mx-auto px-4 py-8">
              <MenuProvider>
                {children}
              </MenuProvider>
              <GoogleAnalytics gaId="G-XXXXXXXXXX" />
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
