import './globals.css'
import { Inter } from 'next/font/google'
import { MenuProvider } from './context/MenuContext'
import GoogleAnalytics from './components/GoogleAnalytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  // Add this line to handle client components
  params,
}: {
  children: React.ReactNode
  params: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuProvider>
          {children}
        </MenuProvider>
        <GoogleAnalytics gaId="G-XXXXXXXXXX" />
      </body>
    </html>
  )
}
